source 'https://rubygems.org'

gem 'rake'
gem'rubocop'
gem 'sinatra'
gem 'rspec'
gem 'capybara'
gem 'pg'
gem 'sqlite3'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-sqlite-adapter'
