DROP DATABASE IF EXISTS dreambnb; 
DROP DATABASE IF EXISTS dreambnb_test; 

CREATE DATABASE dreambnb; 
CREATE DATABASE dreambnb_test;

GRANT ALL PRIVILEGES ON DATABASE dreambnb; 
GRANT ALL PRIVILEGES ON DATABASE dreambnb_test; 
